### ISSUE TITLE
Handling of new/inactive objects

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4567]
Only the active version of objects must be serialized (the most recent consistent state). This is currently not the case. Some objects like `PROG` serialize inactive code: https://github.com/abapGit/abapGit/pull/4564#issuecomment-787032811

1) Clarify requirements

- Output of `serialize` must be the *active* version (any other versions must be ignored)
- Output of `exists` must be `abap_true` if *any* version exists
- Output of `is_active` must be `abap_true` if there's *no inactive* version or inactive = active
- See https://docs.abapgit.org/development/serializers.html (plus #4566)

2) Code review of all serializer classes (priorities)

- All DDIC objects
- All ABAP objects (coding)
- Other Workbench objects
- Any other objects

3) Test any changed objects

- Check, if the test cases at https://github.com/abapGit-tests are up-to-date and update if necessary
- Test (preferably getting https://github.com/abapGit/CI up and running again)

4) Identified issues

- [x] General: Object exists in new or inactive version but there is *no active* version available (#4569)
- [ ] PROG: Returns inactive code (#4657)
- [x] TABL: Returns nothing (#4562)
- [x] DDIC: Error messages (#4584)

**Comment by mbtools** [comment]
The general approach is to raise an exception "No active version found for { type } { name }". This has been implemented for DDIC objects in #4584.
