### ISSUE TITLE
Support for New Object Types

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#5912]
Object types supported by abapGit are listed in the [documentation](https://docs.abapgit.org/ref-supported.html). Instructions for implementing [new object types](https://docs.abapgit.org/development/serializers.html) are also available.

List of requested object types:

- [ ] ACGR: PFCG roles (authorizations) (#3860)
- [ ] AOBJ: Archiving Object (#804)
- [ ] APIS: API type (#5238)
- [ ] AQBG: ABAP Query - User group (#4836)
- [ ] AQQU: ABAP Query - Query (#4837)
- [ ] AQSG: ABAP Query - Functional area (#4838)
- [ ] ASIS: Archiving Information Structure (#1579)
- [ ] BOBF: Business Object Model (#165)
- [ ] CMHC: Cloud Management Health Check (#5602)
- [ ] HTTP: HTTP Service (#5522)
- [ ] OA2S: OAuth2 Scope (#4834)
- [ ] OOPS: Persistence Service classes (#4883)
- [ ] PDAC: Standard rule (#3914)
- [ ] PDTG: Task Group (#3915)
- [ ] PDWS: Workflow Templates (#154)
- [ ] PFAC: Workflow Rules for Agent Determination (#3332)
- [ ] SAJC: Application Job Catalog Entry (#1580)
- [ ] SAJT: Application Job Template (#1581)
- [ ] SHI6/7: IMG structure enhancement (#3077)
- [ ] SKTD: Knowledge Transfer Document - Documentation Infrastructure (#2997)
- [ ] VKOI: Condition Table, Info Structure(#2995)
- [ ] VKOS: Condition Table(#2996)

If you want to implement any of these object types, simply create a PR or reopen the corresponding issue for further discussion.

For object types not listed here, reply to this issue to get them added.

**Comment by ThomasPloski** [comment]
Just wanted to inform you, that object type DRTY will be enabled for abapGit

**Comment by igorchecan** [comment]
Objects from DRC are not supported, could you guys please add these follow objects?
SRFP
SRFQ
SRFR
SRFS

**Comment by larshp** [comment]
> Objects from DRC are not supported, could you guys please add these follow objects? SRFP SRFQ SRFR SRFS

thanks, looks like those object types doesnt exist in the systems I have access to, anyhow, pull requests welcome. There is documentation at https://docs.abapgit.org/development-guide/serializers/overview.html if someone is up for it

**Comment by ViktoriaFreidel** [comment]
Hi, 
I would like to inform you, that new object types UIPG, UIST will be enabled for abapGit:
https://github.com/abapGit/abapGit/issues/6850
https://github.com/abapGit/abapGit/pull/6873

**Comment by Xexer** [comment]
Can't find this one: 
**APLO** Application Log Object

**Comment by pokrakam** [comment]
Another one for the list: Records Management: `SRM1` to `SRM7`
Available in developer edition.

**Comment by mbtools** [comment]
Do you mean "available in ABAP Cloud / abapGit ADT plugin"? That requires SAP to contribute back to here

**Comment by pokrakam** [comment]
No I meant it's available in the NPL 7.52 and A4H 1909 trial/developer systems, probably older ones too.

**Comment by schneidermic0** [comment]
> APLO has an AFF and should be implemented by SAP

I will reach out to my colleagues who are responsible for APLO

**Comment by fvalves** [comment]
I have just created issues #6948 #6949 #6950 , as I'll be working on the enablement of these object types.

**Comment by ViktoriaFreidel** [comment]
Hi,
I would like to inform you, that new object type UIAD will be enabled for abapGit:
https://github.com/abapGit/abapGit/issues/6969

Please be informed the UIAC Object will not have support in abapGit. Description of #5958 is not up today.

**Comment by schneidermic0** [comment]
@fabianlupa I have just reached out to my colleagues, again. As soon as I get some feedback that I can share, I (or maybe they) will let you know here.

**Comment by ThomasPloski** [comment]
> > > APLO has an AFF and should be implemented by SAP
> > 
> > 
> > I will reach out to my colleagues who are responsible for APLO
> 
> Any progress on this @schneidermic0 ? Ran into the same issue that APLO is supported in the abapGit cloud fork but not in the open source version requiring manual installation steps when cloning repos in on-premise systems.

APLO object handler has been provided via PR

**Comment by ThomasPloski** [comment]
Object Handler for object type SAJC has been provided with https://github.com/abapGit/abapGit/pull/7026
Object Handler for object type SAJT has been provided with https://github.com/abapGit/abapGit/pull/7027

**Comment by mbtools** [comment]
Thank you, @ThomasPloski! 

Looks like for most AFF cases, you redefine `changed_by` only. Wouldn't it make sense to ship that part of code on the SAP side? That would allow adding AFF object types by just registering them in AG and we could probably skip creating the object type serializer classes altogether (or only in exceptions).

**Comment by ozgurcglk** [comment]
Hi, is it possible to have abapGit support for object type ELEM ? We can not detect our new works within these objects. If there is a way for me to do it, I can do it too.

**Comment by mbtools** [comment]
@ozgurcglk Please see my [comment](https://github.com/abapGit/abapGit/issues/3162#issuecomment-658361843) on why abapGit does not support BW objects.

**Comment by ozgurcglk** [comment]
Thanks for the reply, I checked it and probably will not go far from there but I would like to try to use the serialize classes to implement the ELEM object only. By the way, it will not be for SDLC purposes, we only need to detect and add these objects to bitbucket.

**Comment by mbtools** [comment]
message me on the abapgit slack

**Comment by mvoros** [comment]
Is there a plan to implement support for object type SRVC - Service Consumption Model? Thanks

**Comment by mbtools** [comment]
SRVC is ABAP file format. Please check with SAP in their aff repo

**Comment by mvoros** [comment]
Hi, thanks for the response but I don't understand it. I created service consumption model. This generated this object + corresponding ABAP class. Both of these objects got added to my transport. When I try to commit them to my Git repo, there is an error message that SRVC is not supported and I can't commit it. I am asking if there is  plan to add support for this object. And you are right, it's a simple JSON file.

**Comment by mbtools** [comment]
Since it is [AFF](https://github.com/SAP/abap-file-formats/tree/main/file-formats/srvc). SAP is responsible for implementing the necessary class for abapGit. You can create an issue to request this at https://github.com/SAP/abap-file-formats/issues

**Comment by HiWiSciFi** [comment]
Object type `SHY6` is marked as "Available" but has not been implemented yet (at least current abapgit_standalone reports it as unavailable).
Am I missing something or has it accidently ended up in the wrong section?

**Comment by mbtools** [comment]
Corrected the mistake. Thx
