### ISSUE TITLE
AFF poc: Translation for INTF

### ISSUE THREAD

**Issue by albertmink** [abapGit/abapGit#6846]
This issue tracks the progress and possible requirements to the POC implementation of translation for ABAP interfaces in the ABAP file formats (AFF).
 
- [x] impl. serialization in #6774
- [x] impl deserialization in #6830 
- [x]  only original language is deserialized to`SEOCLASSTX`, translations are just not deserialized #6983 and #6987

**Comment by mbtools** [comment]
Completed
